sudo: false
language: php

php:
    - 7.1
    - 7.2

before_install:
    - echo yes | pecl upgrade apcu

install:
    - travis_retry composer update --no-interaction --prefer-dist

script: ./vendor/bin/phpunit
